log_level: 1
database:
  dialect: sqlite
  filename: ./data/test.db
bots:
  - context: kook
    name: kook-bot
    token: ${KOOK_TOKEN}
  - name: zhin-qq
    context: qq
    appid: ${QQ_APPID}
    secret: ${QQ_SECRET}
    removeAt: true
    sandbox: false
    mode: websocket
    intents:
      - GUILDS
      - PUBLIC_GUILD_MESSAGES
      - GUILD_MESSAGE_REACTIONS
      - DIRECT_MESSAGE
      - GROUP_AT_MESSAGE_CREATE
      - C2C_MESSAGE_CREATE
      - INTERACTION
    data_dir: /Users/liuchunlang/IdeaProjects/zhin/examples/test-bot/data
plugin_dirs:
  - node_modules
  - ./src/plugins
services:
  - process
  - config
  - command
  - component
  - permission
  - cron
plugins:
  - test-plugin
  - test-jsx
  - memory-debug
  - plugin-memory-profiler
  - "@zhin.js/http"
  - "@zhin.js/mcp"
  - "@zhin.js/plugin-github-notify"
  - "@zhin.js/adapter-sandbox"
  - "@zhin.js/adapter-kook"
  - "@zhin.js/adapter-qq"
http:
  port: 8086
  username: ${username}
  password: ${password}
  base: /api
console:
  enabled: true
  lazyLoad: true
