log_level: 1
database:
  dialect: sqlite
  filename: ./data/test.db
plugin_dirs:
  - node_modules
  - ./src/plugins
plugins:
  - test-plugin
  - test-jsx
  - "@zhin.js/http"
  - "@zhin.js/console"
  - "@zhin.js/adapter-sandbox"
http:
  port: 8086
  username: admin
  password: admin123
  base: /api
